/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccordionContent: typeof import('reka-ui')['AccordionContent']
    AccordionHeader: typeof import('reka-ui')['AccordionHeader']
    AccordionItem: typeof import('reka-ui')['AccordionItem']
    AccordionRoot: typeof import('reka-ui')['AccordionRoot']
    AccordionTrigger: typeof import('reka-ui')['AccordionTrigger']
    DataProperties: typeof import('./components/data/properties/DataProperties.vue')['default']
    IconArrowRight: typeof import('./components/icons/IconArrowRight.vue')['default']
    IconChevronRight: typeof import('./components/icons/IconChevronRight.vue')['default']
    IconCollection: typeof import('./components/icons/IconCollection.vue')['default']
    IconGridOrthographic: typeof import('./components/icons/IconGridOrthographic.vue')['default']
    IconGridPerspective: typeof import('./components/icons/IconGridPerspective.vue')['default']
    IconImport: typeof import('./components/icons/IconImport.vue')['default']
    IconLMB: typeof import('./components/icons/IconLMB.vue')['default']
    IconMaterialData: typeof import('./components/icons/IconMaterialData.vue')['default']
    IconMixeur: typeof import('./components/icons/IconMixeur.vue')['default']
    IconMMB: typeof import('./components/icons/IconMMB.vue')['default']
    IconObjectData: typeof import('./components/icons/IconObjectData.vue')['default']
    IconViewOrtho: typeof import('./components/icons/view/IconViewOrtho.vue')['default']
    IconViewPerspective: typeof import('./components/icons/view/IconViewPerspective.vue')['default']
    KeymapInformation: typeof import('./components/status/KeymapInformation.vue')['default']
    MaterialProperties: typeof import('./components/data/properties/MaterialProperties.vue')['default']
    MenuBar: typeof import('./components/header/MenuBar.vue')['default']
    MenubarContent: typeof import('reka-ui')['MenubarContent']
    MenubarItem: typeof import('reka-ui')['MenubarItem']
    MenubarMenu: typeof import('reka-ui')['MenubarMenu']
    MenubarRoot: typeof import('reka-ui')['MenubarRoot']
    MenubarSub: typeof import('reka-ui')['MenubarSub']
    MenubarSubContent: typeof import('reka-ui')['MenubarSubContent']
    MenubarSubTrigger: typeof import('reka-ui')['MenubarSubTrigger']
    MenubarTrigger: typeof import('reka-ui')['MenubarTrigger']
    MOutliner: typeof import('./components/data/outliner/MOutliner.vue')['default']
    MSidebar: typeof import('./components/sidebar/MSidebar.vue')['default']
    MViewport: typeof import('./components/viewport/MViewport.vue')['default']
    NumberFieldDecrement: typeof import('reka-ui')['NumberFieldDecrement']
    NumberFieldIncrement: typeof import('reka-ui')['NumberFieldIncrement']
    NumberFieldInput: typeof import('reka-ui')['NumberFieldInput']
    NumberFieldRoot: typeof import('reka-ui')['NumberFieldRoot']
    ObjectProperties: typeof import('./components/data/properties/object/ObjectProperties.vue')['default']
    ObjectSettings: typeof import('./components/sidebar/ObjectSettings.vue')['default']
    OutlinerItem: typeof import('./components/data/outliner/OutlinerItem.vue')['default']
    SplashScreen: typeof import('./components/modals/SplashScreen.vue')['default']
    StatusBar: typeof import('./components/status/StatusBar.vue')['default']
    TabsContent: typeof import('reka-ui')['TabsContent']
    TabsList: typeof import('reka-ui')['TabsList']
    TabsRoot: typeof import('reka-ui')['TabsRoot']
    TabsTrigger: typeof import('reka-ui')['TabsTrigger']
    TopBar: typeof import('./components/header/TopBar.vue')['default']
    TransformLocation: typeof import('./components/data/properties/object/transform/TransformLocation.vue')['default']
    ViewNavigationWidget: typeof import('./components/viewport/ViewNavigationWidget.vue')['default']
  }
}
