// Auto-generated file. Do not edit manually.
// Generated at: 2026-02-14T15:51:42.148Z
// Total icons: 57

declare global {
	type MxIconName =
		| 'base/arrow-right'
		| 'base/triangle-down'
		| 'base/triangle-right'
		| 'keys/lmb'
		| 'keys/mmb'
		| 'light/light'
		| 'light/light-area'
		| 'light/light-point'
		| 'light/light-spot'
		| 'light/light-sun'
		| 'mesh/mesh'
		| 'mesh/mesh-circle'
		| 'mesh/mesh-cone'
		| 'mesh/mesh-cube'
		| 'mesh/mesh-cylinder'
		| 'mesh/mesh-icosphere'
		| 'mesh/mesh-plane'
		| 'mesh/mesh-sphere'
		| 'mesh/mesh-torus'
		| 'misc/export'
		| 'misc/eye-dropper'
		| 'misc/full-screen'
		| 'misc/github'
		| 'misc/text'
		| 'misc/url'
		| 'misc/visibility-hidden'
		| 'misc/visibility-visible'
		| 'outliner/empty'
		| 'outliner/group'
		| 'outliner/outliner'
		| 'properties/camera-properties'
		| 'properties/data-properties'
		| 'properties/geometry-properties'
		| 'properties/light-properties'
		| 'properties/properties'
		| 'properties/text-properties'
		| 'shading/shading-preview'
		| 'shading/shading-rendered'
		| 'shading/shading-solid'
		| 'shading/shading-wireframe'
		| 'toolbar/tool-move'
		| 'toolbar/tool-rotate'
		| 'toolbar/tool-scale'
		| 'ui/arrow-right'
		| 'ui/asset-browser'
		| 'ui/checkbox-checked'
		| 'ui/checkbox-unchecked'
		| 'ui/checkmark'
		| 'ui/chevron-right'
		| 'ui/collection'
		| 'ui/import'
		| 'ui/material-data'
		| 'ui/object-data'
		| 'ui/render-image'
		| 'ui/viewport'
		| 'view/view-orthographic'
		| 'view/view-perspective'
}

export {}
